# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, meeyoungchoi-patch-3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout backend
        uses: actions/checkout@v2
      - name: checkout frontend
        uses: actions/checkout@v2
        with:
          repository: Couch-Coders/8th-ooLa-fe
          path: ./frontend
      - uses: actions/setup-java@v2
        with:
         distribution: 'temurin'
         java-version: '11'
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      - name: build frontend to resources
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          mkdir src/main/resources/static/
          cp -r frontent/build/* src/main/resources/static/
        env:
          CI: ""
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: studyoola
          heroku_email: goodlife1359@gmail.com
